[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.24", features = ["json", "native-tls"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.2"
tokio = { version = "1.0", features = ["full"] }